# Generated by Django 5.1.7 on 2025-03-28 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0007_alter_reservoir_options_remove_reservoir_in_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
            ],
            options={
                'verbose_name': 'Ishlab chiqarish turi',
                'verbose_name_plural': 'Ishlab chiqarish turlari',
            },
        ),
        migrations.CreateModel(
            name='ProductionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_number', models.CharField(max_length=50, verbose_name='Jarayon raqami')),
                ('process_type', models.CharField(choices=[('raw_processing', 'Xom-ashyoni qayta ishlash'), ('mixing', "Qo'shimchalar qo'shish")], max_length=20, verbose_name='Jarayon turi')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('input_reservoir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_inputs', to='warehouse.reservoir', verbose_name='Kirish rezervuari')),
                ('output_reservoir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_outputs', to='warehouse.reservoir', verbose_name='Chiqish rezervuari')),
            ],
            options={
                'verbose_name': 'Ishlab chiqarish jarayoni',
                'verbose_name_plural': 'Ishlab chiqarish jarayonlari',
            },
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Miqdor (tonna)')),
                ('temperature', models.FloatField(default=20, verbose_name='Harorat (C)')),
                ('density', models.FloatField(verbose_name='Zichlik (kg/m³)')),
                ('liter_volume', models.FloatField(verbose_name='Hajm (litr)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Mahsulot')),
                ('production_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='production.productionprocess', verbose_name='Ishlab chiqarish jarayoni')),
            ],
            options={
                'verbose_name': 'Ishlab chiqarilgan mahsulot',
                'verbose_name_plural': 'Ishlab chiqarilgan mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='ProductionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Miqdor (tonna)')),
                ('temperature', models.FloatField(default=20, verbose_name='Harorat (C)')),
                ('density', models.FloatField(verbose_name='Zichlik (kg/m³)')),
                ('liter_volume', models.FloatField(verbose_name='Hajm (litr)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Material')),
                ('production_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='production.productionprocess', verbose_name='Ishlab chiqarish jarayoni')),
            ],
            options={
                'verbose_name': 'Ishlab chiqarish uchun kiruvchi material',
                'verbose_name_plural': 'Ishlab chiqarish uchun kiruvchi materiallar',
            },
        ),
        migrations.CreateModel(
            name='GasolineMixing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_quantity', models.FloatField(verbose_name='Ishlab chiqarilgan miqdor (tonna)')),
                ('temperature', models.FloatField(default=20, verbose_name='Harorat (C)')),
                ('density', models.FloatField(verbose_name='Zichlik (kg/m³)')),
                ('liter_volume', models.FloatField(verbose_name='Hajm (litr)')),
                ('gasoline_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_gasoline_type', to='warehouse.product', verbose_name='Benzin turi')),
                ('production_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gasoline_mixing', to='production.productionprocess', verbose_name='Ishlab chiqarish jarayoni')),
            ],
            options={
                'verbose_name': 'Benzin aralashmasini tayyorlash',
                'verbose_name_plural': 'Benzin aralashmasini tayyorlash jarayonlari',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('additive', "Qo'shimcha"), ('product', 'Tayyor mahsulot')], max_length=20, verbose_name='Ishlab chiqarilgan mahsulot turi')),
                ('raw_material_quantity', models.FloatField(verbose_name='Xom-ashyo miqdori (tonna)')),
                ('temperature', models.FloatField(default=20, verbose_name='Harorat (C)')),
                ('density', models.FloatField(verbose_name='Zichlik (kg/m³)')),
                ('liter_volume', models.FloatField(verbose_name='Hajm (litr)')),
                ('loss_percentage', models.FloatField(default=0, verbose_name="Yo'qotish foizi (%)")),
                ('calculated_loss', models.FloatField(default=0, verbose_name="Hisoblangan yo'qotish (tonna)")),
                ('production_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_processing', to='production.productionprocess', verbose_name='Ishlab chiqarish jarayoni')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_raw_material', to='warehouse.product', verbose_name='Xom-ashyo')),
            ],
            options={
                'verbose_name': 'Xom-ashyoni qayta ishlash',
                'verbose_name_plural': 'Xom-ashyoni qayta ishlash jarayonlari',
            },
        ),
    ]
