# Generated by Django 5.1.7 on 2025-03-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('warehouse', '0007_alter_reservoir_options_remove_reservoir_in_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionprocess',
            name='input_source_type',
            field=models.CharField(choices=[('reservoir', 'Rezervuar'), ('wagon', 'Vagon')], default='reservoir', max_length=10, verbose_name='Kirish manba turi'),
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='input_wagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_inputs', to='warehouse.wagon', verbose_name='Kirish vagoni'),
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='output_source_type',
            field=models.CharField(choices=[('reservoir', 'Rezervuar'), ('wagon', 'Vagon')], default='reservoir', max_length=10, verbose_name='Chiqish manba turi'),
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='output_wagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_outputs', to='warehouse.wagon', verbose_name='Chiqish vagoni'),
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='input_reservoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_inputs', to='warehouse.reservoir', verbose_name='Kirish rezervuari'),
        ),
        migrations.AlterField(
            model_name='productionprocess',
            name='output_reservoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_outputs', to='warehouse.reservoir', verbose_name='Chiqish rezervuari'),
        ),
    ]
