from django.urls import path
from .views import (
    index, dashboard, MovementReportView,
    ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView,
    WagonListView, MovementListView, InventoryListView,
    MovementCreateView,
    BatchListView, BatchDetailView, BatchCreateView, BatchUpdateView,
    export_products_excel, export_movements_excel, export_wagons_excel ,ReservoirCreateView, ReservoirListView, ReservoirDetailView, 
    ReservoirUpdateView,ReservoirMovementListView, ReservoirMovementCreateView,LocalClientListView, LocalClientCreateView,
    LocalMovementListView, LocalMovementCreateView,PlacementCreateView, PlacementListView, PlacementUpdateView,WagonDetailView,ClientCreateView,
    ClientListView,ProductInventoryReportView, WagonTypeListView, WagonTypeCreateView, WagonTypeUpdateView,
    MovementUpdateView, movement_delete, recalculate_product_inventory_view, recalculate_all_inventories, recalculate_all_reservoirs, recalculate_all_wagons,
    export_reservoirs_excel,
    estokada_dashboard, estokada_reception_list, estokada_reception_process, estokada_sales_list, estokada_sales_process, estokada_production_list, estokada_production_process, estokada_transfer_list, estokada_transfer_process,
    sales_department_dashboard, sales_movement_create, sales_reception_list, sales_sales_list, sales_production_list, sales_transfer_list, sales_movement_detail, sales_movement_edit, sales_movement_confirm, sales_movement_cancel,
    AnalyticsDashboardView, GenerateReportView, UpdateAnalyticsDataView,
    InventoryAuditListView, InventoryAuditCreateView, InventoryAuditDetailView, InventoryAuditUpdateView, InventoryAuditStartView, InventoryAuditCompleteView, InventoryAuditCancelView, InventoryAuditReportView, export_audit_to_excel, InventoryAuditItemUpdateView,
    ProductMinLevelListView, ProductMinLevelCreateView, ProductMinLevelUpdateView, ProductMinLevelDeleteView,
    StockForecastListView, StockForecastView, ProductForecastDetailView,
    PurchasePlanListView, PurchasePlanCreateView, PurchasePlanDetailView, PurchasePlanUpdateView, PurchasePlanApproveView, PurchasePlanStartView, PurchasePlanCompleteView, PurchasePlanCancelView, export_purchase_plan_to_excel,
    SupplierListView, SupplierCreateView, SupplierDetailView, SupplierUpdateView, SupplierDeleteView,
    SupplierRatingCreateView, ProductSupplierListView, ProductSupplierCreateView, ProductSupplierUpdateView, ProductSupplierDeleteView,
    OrderPointListView, OrderPointCreateView, OrderPointDetailView, OrderPointUpdateView, OrderPointDeleteView,
    PurchaseNotificationListView, PurchaseNotificationCreateView, GenerateNotificationsView, PurchaseNotificationDetailView, PurchaseNotificationUpdateView, PurchaseNotificationStatusUpdateView
)

app_name = 'warehouse'

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/', dashboard, name='dashboard'),
    path('movements/report/', MovementReportView.as_view(), name='movement_report'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/recalculate/', recalculate_product_inventory_view, name='recalculate_product_inventory'),
    path('products/recalculate-all/', recalculate_all_inventories, name='recalculate_all_inventories'),
    path('wagons/', WagonListView.as_view(), name='wagon_list'),
    path('movements/', MovementListView.as_view(), name='movement_list'),
    path('movements/create/',MovementCreateView.as_view(), name='movement_create'),
    path('inventory/', InventoryListView.as_view(), name='inventory_list'),
    path('batches/', BatchListView.as_view(), name='batch_list'),
    path('batches/create/', BatchCreateView.as_view(), name='batch_create'),
    path('batches/<int:pk>/', BatchDetailView.as_view(), name='batch_detail'),
    path('batches/<int:pk>/update/', BatchUpdateView.as_view(), name='batch_update'),
    path('export/products/excel/', export_products_excel, name='export_products_excel'),
    path('export/movements/excel/', export_movements_excel, name='export_movements_excel'),
    path('export/wagons/excel/', export_wagons_excel, name='export_wagons_excel'),
    path('reservoirs/', ReservoirListView.as_view(), name='reservoir_list'),
    path('reservoirs/create/', ReservoirCreateView.as_view(), name='reservoir_create'),
    path('reservoirs/<int:pk>/', ReservoirDetailView.as_view(), name='reservoir_detail'),
    path('reservoirs/<int:pk>/update/', ReservoirUpdateView.as_view(), name='reservoir_update'),
    path('reservoir-movements/', ReservoirMovementListView.as_view(), name='reservoir_movement_list'),
    path('reservoir-movements/create/', ReservoirMovementCreateView.as_view(), name='reservoir_movement_create'),
    path('product-inventory/', ProductInventoryReportView.as_view(), name='product_inventory_report'),
    path('local-clients/', LocalClientListView.as_view(), name='localclient_list'),
    path('local-clients/create/', LocalClientCreateView.as_view(), name='localclient_create'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('local-movements/', LocalMovementListView.as_view(), name='localmovement_list'),
    path('local-movements/create/', LocalMovementCreateView.as_view(), name='localmovement_create'),
    path('placements/', PlacementListView.as_view(), name='placement_list'),
    path('placements/create/', PlacementCreateView.as_view(), name='placement_create'),
    path('placements/<int:pk>/update/', PlacementUpdateView.as_view(), name='placement_update'),
    path('wagons/<int:pk>/', WagonDetailView.as_view(), name='wagon_detail'),
    path('wagon-types/', WagonTypeListView.as_view(), name='wagon_type_list'),
    path('wagon-types/create/', WagonTypeCreateView.as_view(), name='wagon_type_create'),
    path('wagon-types/<int:pk>/update/', WagonTypeUpdateView.as_view(), name='wagon_type_update'),
    path('movements/<int:pk>/update/', MovementUpdateView.as_view(), name='movement_update'),
    path('movements/<int:pk>/delete/', movement_delete, name='movement_delete'),
    path('reservoirs/recalculate-all/', recalculate_all_reservoirs, name='recalculate_all_reservoirs'),
    path('wagons/recalculate-all/', recalculate_all_wagons, name='recalculate_all_wagons'),
    path('export/reservoirs/excel/', export_reservoirs_excel, name='export_reservoirs_excel'),
    path('estokada/', estokada_dashboard, name='estokada_dashboard'),
    path('estokada/reception/', estokada_reception_list, name='estokada_reception_list'),
    path('estokada/reception/<int:pk>/process/', estokada_reception_process, name='estokada_reception_process'),
    path('estokada/sales/', estokada_sales_list, name='estokada_sales_list'),
    path('estokada/sales/<int:pk>/process/', estokada_sales_process, name='estokada_sales_process'),
    path('estokada/production/', estokada_production_list, name='estokada_production_list'),
    path('estokada/production/<int:pk>/process/', estokada_production_process, name='estokada_production_process'),
    path('estokada/transfer/', estokada_transfer_list, name='estokada_transfer_list'),
    path('estokada/transfer/<int:pk>/process/', estokada_transfer_process, name='estokada_transfer_process'),
    path('sales/', sales_department_dashboard, name='sales_department_dashboard'),
    path('sales/movement/create/', sales_movement_create, name='sales_movement_create'),
    path('sales/reception/', sales_reception_list, name='sales_reception_list'),
    path('sales/sales/', sales_sales_list, name='sales_sales_list'),
    path('sales/production/', sales_production_list, name='sales_production_list'),
    path('sales/transfer/', sales_transfer_list, name='sales_transfer_list'),
    path('sales/movement/<int:pk>/', sales_movement_detail, name='sales_movement_detail'),
    path('sales/movement/<int:pk>/edit/', sales_movement_edit, name='sales_movement_edit'),
    path('sales/movement/<int:pk>/confirm/', sales_movement_confirm, name='sales_movement_confirm'),
    path('sales/movement/<int:pk>/cancel/', sales_movement_cancel, name='sales_movement_cancel'),
    path('analytics/', AnalyticsDashboardView.as_view(), name='analytics_dashboard'),
    path('analytics/generate-report/', GenerateReportView.as_view(), name='generate_report'),
    path('analytics/update/', UpdateAnalyticsDataView.as_view(), name='update_analytics'),
    path('inventory/audit/', InventoryAuditListView.as_view(), name='audit_list'),
    path('inventory/audit/create/', InventoryAuditCreateView.as_view(), name='audit_create'),
    path('inventory/audit/<int:pk>/', InventoryAuditDetailView.as_view(), name='audit_detail'),
    path('inventory/audit/<int:pk>/update/', InventoryAuditUpdateView.as_view(), name='audit_update'),
    path('inventory/audit/<int:pk>/start/', InventoryAuditStartView.as_view(), name='audit_start'),
    path('inventory/audit/<int:pk>/complete/', InventoryAuditCompleteView.as_view(), name='audit_complete'),
    path('inventory/audit/<int:pk>/cancel/', InventoryAuditCancelView.as_view(), name='audit_cancel'),
    path('inventory/audit/<int:pk>/report/', InventoryAuditReportView.as_view(), name='audit_report'),
    path('inventory/audit/<int:pk>/export/', export_audit_to_excel, name='export_audit'),
    path('inventory/audit/item/<int:pk>/update/', InventoryAuditItemUpdateView.as_view(), name='audit_item_update'),
    path('inventory/min-levels/', ProductMinLevelListView.as_view(), name='min_level_list'),
    path('inventory/min-levels/create/<int:product_id>/', ProductMinLevelCreateView.as_view(), name='min_level_create'),
    path('inventory/min-levels/<int:pk>/update/', ProductMinLevelUpdateView.as_view(), name='min_level_update'),
    path('inventory/min-levels/<int:pk>/delete/', ProductMinLevelDeleteView.as_view(), name='min_level_delete'),
    path('inventory/forecast/', StockForecastListView.as_view(), name='forecast_list'),
    path('inventory/forecast/generate/', StockForecastView.as_view(), name='forecast_generate'),
    path('inventory/forecast/product/<int:pk>/', ProductForecastDetailView.as_view(), name='product_forecast'),
    path('inventory/purchase-plan/', PurchasePlanListView.as_view(), name='purchase_plan_list'),
    path('inventory/purchase-plan/create/', PurchasePlanCreateView.as_view(), name='purchase_plan_create'),
    path('inventory/purchase-plan/<int:pk>/', PurchasePlanDetailView.as_view(), name='purchase_plan_detail'),
    path('inventory/purchase-plan/<int:pk>/update/', PurchasePlanUpdateView.as_view(), name='purchase_plan_update'),
    path('inventory/purchase-plan/<int:pk>/approve/', PurchasePlanApproveView.as_view(), name='purchase_plan_approve'),
    path('inventory/purchase-plan/<int:pk>/start/', PurchasePlanStartView.as_view(), name='purchase_plan_start'),
    path('inventory/purchase-plan/<int:pk>/complete/', PurchasePlanCompleteView.as_view(), name='purchase_plan_complete'),
    path('inventory/purchase-plan/<int:pk>/cancel/', PurchasePlanCancelView.as_view(), name='purchase_plan_cancel'),
    path('inventory/purchase-plan/<int:pk>/export/', export_purchase_plan_to_excel, name='export_purchase_plan'),
    path('purchasing/suppliers/', SupplierListView.as_view(), name='supplier_list'),
    path('purchasing/suppliers/create/', SupplierCreateView.as_view(), name='supplier_create'),
    path('purchasing/suppliers/<int:pk>/', SupplierDetailView.as_view(), name='supplier_detail'),
    path('purchasing/suppliers/<int:pk>/update/', SupplierUpdateView.as_view(), name='supplier_update'),
    path('purchasing/suppliers/<int:pk>/delete/', SupplierDeleteView.as_view(), name='supplier_delete'),
    path('purchasing/suppliers/ratings/create/', SupplierRatingCreateView.as_view(), name='supplier_rating_create'),
    path('purchasing/suppliers/<int:supplier_id>/ratings/create/', SupplierRatingCreateView.as_view(), name='supplier_rating_create_for_supplier'),
    path('purchasing/product-suppliers/', ProductSupplierListView.as_view(), name='product_supplier_list'),
    path('purchasing/product-suppliers/create/', ProductSupplierCreateView.as_view(), name='product_supplier_create'),
    path('purchasing/product-suppliers/<int:pk>/update/', ProductSupplierUpdateView.as_view(), name='product_supplier_update'),
    path('purchasing/product-suppliers/<int:pk>/delete/', ProductSupplierDeleteView.as_view(), name='product_supplier_delete'),
    path('purchasing/order-points/', OrderPointListView.as_view(), name='order_point_list'),
    path('purchasing/order-points/create/', OrderPointCreateView.as_view(), name='order_point_create'),
    path('purchasing/order-points/<int:pk>/', OrderPointDetailView.as_view(), name='order_point_detail'),
    path('purchasing/order-points/<int:pk>/update/', OrderPointUpdateView.as_view(), name='order_point_update'),
    path('purchasing/order-points/<int:pk>/delete/', OrderPointDeleteView.as_view(), name='order_point_delete'),
    path('purchasing/notifications/', PurchaseNotificationListView.as_view(), name='purchase_notification_list'),
    path('purchasing/notifications/create/', PurchaseNotificationCreateView.as_view(), name='purchase_notification_create'),
    path('purchasing/notifications/generate/', GenerateNotificationsView.as_view(), name='generate_notifications'),
    path('purchasing/notifications/<int:pk>/', PurchaseNotificationDetailView.as_view(), name='purchase_notification_detail'),
    path('purchasing/notifications/<int:pk>/update/', PurchaseNotificationUpdateView.as_view(), name='purchase_notification_update'),
    path('purchasing/notifications/<int:pk>/status/<str:status>/', PurchaseNotificationStatusUpdateView.as_view(), name='purchase_notification_status_update'),
]
