# Generated by Django 5.1.7 on 2025-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Манзил'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_joined_company',
            field=models.DateField(blank=True, null=True, verbose_name='Ишга қабул қилинган сана'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Туғилган санаси'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Тасдиқланган аккаунт'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Лавозими'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отасининг исми'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Қўшимча изоҳлар'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон рақами'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/', verbose_name='Фойдаланувчи расми'),
        ),
    ]
