# Generated by Django 5.1.7 on 2025-04-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_role_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Администратор'), ('boss', 'Директор'), ('sales', 'Отдел продаж'), ('finance', 'Финансовый отдел'), ('estokada', 'Эстокада'), ('accounting', 'Бухгалтерия'), ('customs', 'Отдел таможни')], max_length=20, null=True, verbose_name='Роль пользователя'),
        ),
    ]
