# Generated by Django 5.1.7 on 2025-04-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Администратор'), ('boss', 'Директор'), ('sales', 'Отдел продаж'), ('finance', 'Финансовый отдел'), ('estokada', 'Эстокада'), ('accounting', 'Бухгалтерия'), ('customs', 'Отдел таможни'), ('infrastructure', 'Инфраструктура')], max_length=20, null=True, verbose_name='Роль пользователя'),
        ),
    ]
