# Generated by Django 5.1.7 on 2025-05-05 18:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('type', models.CharField(choices=[('asset', 'Актив'), ('liability', 'Пассив'), ('equity', 'Капитал'), ('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория счета',
                'verbose_name_plural': 'Категории счетов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('income', 'Daromad'), ('expense', 'Xarajat')], max_length=10, verbose_name='Turi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ikonka')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rang')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Финансовый период',
                'verbose_name_plural': 'Финансовые периоды',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('movement_type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], max_length=3, verbose_name='Тип движения')),
                ('quantity', models.FloatField(default=0, verbose_name='Количество')),
                ('total_price_usd', models.FloatField(default=0, verbose_name='Сумма (USD)')),
                ('total_price_sum', models.FloatField(default=0, verbose_name='Сумма (сум)')),
            ],
            options={
                'verbose_name': 'Финансовая запись',
                'verbose_name_plural': 'Финансовые записи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('default_payment_term', models.IntegerField(default=30, verbose_name='Срок оплаты по умолчанию (дни)')),
                ('invoice_prefix', models.CharField(default='INV', max_length=10, verbose_name='Префикс номера счета')),
                ('next_invoice_number', models.IntegerField(default=1, verbose_name='Следующий номер счета')),
                ('fiscal_year_start', models.DateField(verbose_name='Начало финансового года')),
                ('currency_symbol', models.CharField(default='UZS', max_length=5, verbose_name='Символ валюты')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Настройка бухгалтерии',
                'verbose_name_plural': 'Настройки бухгалтерии',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('sales', 'Продажа'), ('purchase', 'Закупка')], max_length=10, verbose_name='Тип счета')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер счета')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выставления')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Подытог')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма налога')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма скидки')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итого')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='draft', max_length=10, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Условия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Счет-фактура',
                'verbose_name_plural': 'Счета-фактуры',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ставка налога (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма налога')),
            ],
            options={
                'verbose_name': 'Позиция счета',
                'verbose_name_plural': 'Позиции счета',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='Номер операции')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведено'), ('cancelled', 'Отменено')], default='draft', max_length=10, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Бухгалтерская проводка',
                'verbose_name_plural': 'Бухгалтерские проводки',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковский перевод'), ('card', 'Банковская карта'), ('other', 'Другое')], max_length=10, verbose_name='Способ оплаты')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер платежа')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка (%)')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ставка налога',
                'verbose_name_plural': 'Ставки налогов',
                'ordering': ['rate'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('transfer', 'Перевод')], max_length=10, verbose_name='Тип транзакции')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Теги')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер ссылки')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Дебет')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Кредит')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код счета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.accountcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('period', models.CharField(choices=[('day', 'Kunlik'), ('week', 'Haftalik'), ('month', 'Oylik'), ('year', 'Yillik')], max_length=10, verbose_name='Davr')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Byudjet',
                'verbose_name_plural': 'Byudjetlar',
                'ordering': ['-start_date'],
            },
        ),
    ]
