# Generated by Django 5.1.7 on 2025-04-10 16:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('warehouse', '0013_supplier_orderpoint_purchasenotification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('type', models.CharField(choices=[('asset', 'Актив'), ('liability', 'Пассив'), ('equity', 'Капитал'), ('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория счета',
                'verbose_name_plural': 'Категории счетов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка (%)')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ставка налога',
                'verbose_name_plural': 'Ставки налогов',
                'ordering': ['rate'],
            },
        ),
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Финансовая запись', 'verbose_name_plural': 'Финансовые записи'},
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], max_length=3, verbose_name='Тип движения'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='total_price_sum',
            field=models.FloatField(default=0, verbose_name='Сумма (сум)'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='total_price_usd',
            field=models.FloatField(default=0, verbose_name='Сумма (USD)'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код счета')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.accountcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL, verbose_name='Закрыто')),
            ],
            options={
                'verbose_name': 'Финансовый период',
                'verbose_name_plural': 'Финансовые периоды',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('sales', 'Продажа'), ('purchase', 'Закупка')], max_length=10, verbose_name='Тип счета')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер счета')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выставления')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Подытог')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма налога')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма скидки')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итого')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='draft', max_length=10, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Условия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_invoices', to='warehouse.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='warehouse.movement', verbose_name='Операция склада')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='warehouse.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Счет-фактура',
                'verbose_name_plural': 'Счета-фактуры',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ставка налога (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма налога')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.invoice', verbose_name='Счет-фактура')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция счета',
                'verbose_name_plural': 'Позиции счета',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='Номер операции')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведено'), ('cancelled', 'Отменено')], default='draft', max_length=10, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='accounting.invoice', verbose_name='Счет-фактура')),
                ('local_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='warehouse.localmovement', verbose_name='Локальная операция')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='warehouse.movement', verbose_name='Операция склада')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_entries', to=settings.AUTH_USER_MODEL, verbose_name='Проведено')),
                ('reservoir_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='warehouse.reservoirmovement', verbose_name='Операция резервуара')),
            ],
            options={
                'verbose_name': 'Бухгалтерская проводка',
                'verbose_name_plural': 'Бухгалтерские проводки',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='accounting.journalentry', verbose_name='Проводка'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковский перевод'), ('card', 'Банковская карта'), ('other', 'Другое')], max_length=10, verbose_name='Способ оплаты')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер платежа')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.invoice', verbose_name='Счет-фактура')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('default_payment_term', models.IntegerField(default=30, verbose_name='Срок оплаты по умолчанию (дни)')),
                ('invoice_prefix', models.CharField(default='INV', max_length=10, verbose_name='Префикс номера счета')),
                ('next_invoice_number', models.IntegerField(default=1, verbose_name='Следующий номер счета')),
                ('fiscal_year_start', models.DateField(verbose_name='Начало финансового года')),
                ('currency_symbol', models.CharField(default='UZS', max_length=5, verbose_name='Символ валюты')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('default_credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_credit_settings', to='accounting.account', verbose_name='Счет кредита по умолчанию')),
                ('default_debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_debit_settings', to='accounting.account', verbose_name='Счет дебета по умолчанию')),
                ('default_tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_settings', to='accounting.taxrate', verbose_name='Ставка налога по умолчанию')),
            ],
            options={
                'verbose_name': 'Настройка бухгалтерии',
                'verbose_name_plural': 'Настройки бухгалтерии',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Дебет')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Кредит')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер ссылки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.account', verbose_name='Счет')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.journalentry', verbose_name='Проводка')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
