# Generated by Django 5.1.7 on 2025-04-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountcategory_taxrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('income', 'Daromad'), ('expense', 'Xarajat')], max_length=10, verbose_name='Turi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ikonka')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rang')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Summa')),
                ('period', models.CharField(choices=[('day', 'Kunlik'), ('week', 'Haftalik'), ('month', 'Oylik'), ('year', 'Yillik')], max_length=10, verbose_name='Davr')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Byudjet',
                'verbose_name_plural': 'Byudjetlar',
                'ordering': ['-start_date'],
            },
        ),
    ]
