# Generated by Django 5.1.7 on 2025-05-05 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Номер контракта')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('fulfilled', 'Выполнен'), ('expired', 'Истек'), ('terminated', 'Расторгнут')], default='draft', max_length=20, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_contracts', to='warehouse.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Простой контракт',
                'verbose_name_plural': 'Простые контракты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='Номер заказа')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('delivery_status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('in_progress', 'В процессе доставки'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус доставки')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('partial', 'Частично оплачен'), ('paid', 'Полностью оплачен'), ('overdue', 'Просрочен'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Общая сумма')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Оплаченная сумма')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('shipping_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Способ доставки')),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Способ оплаты')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=100, unique=True, verbose_name='Номер платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата платежа')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('bank_transfer', 'Банковский перевод'), ('card', 'Карта'), ('online', 'Онлайн платеж'), ('credit', 'Кредит/Рассрочка'), ('other', 'Другое')], default='bank_transfer', max_length=20, verbose_name='Тип платежа')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Выполнен'), ('failed', 'Ошибка'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Реквизиты платежа')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Номер контракта')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Общая сумма')),
                ('currency', models.CharField(choices=[('UZS', 'Сум'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Рубль')], default='UZS', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('fulfilled', 'Выполнен'), ('expired', 'Истек'), ('terminated', 'Расторгнут')], default='draft', max_length=20, verbose_name='Статус')),
                ('payment_terms', models.TextField(blank=True, null=True, verbose_name='Условия оплаты')),
                ('delivery_terms', models.TextField(blank=True, null=True, verbose_name='Условия доставки')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл контракта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='warehouse.client', verbose_name='Клиент')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.salescontract', verbose_name='Контракт'),
        ),
        migrations.CreateModel(
            name='SalesContractProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Общая сумма')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.salescontract', verbose_name='Контракт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт контракта',
                'verbose_name_plural': 'Продукты контракта',
            },
        ),
        migrations.CreateModel(
            name='SalesMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер счета-фактуры')),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за единицу')),
                ('currency', models.CharField(choices=[('UZS', 'Сум'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Рубль')], default='UZS', max_length=3, verbose_name='Валюта')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Общая сумма')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Скидка (%)')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Сумма скидки')),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Налог (%)')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Сумма налога')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('transport_type', models.CharField(blank=True, choices=[('auto', 'Автомобильный'), ('rail', 'Железнодорожный'), ('sea', 'Морской'), ('air', 'Воздушный'), ('pipeline', 'Трубопроводный'), ('other', 'Другой')], max_length=50, null=True, verbose_name='Тип транспорта')),
                ('transport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер транспорта')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер контракта')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('estimated_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Расчетная прибыль')),
                ('estokada_processed', models.BooleanField(default=False, verbose_name='Обработано эстокадой')),
                ('is_export', models.BooleanField(default=False, verbose_name='Экспортная продажа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.client', verbose_name='Клиент')),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_details', to='warehouse.movement', verbose_name='Основное движение')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sales', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-movement__date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Общая сумма')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='sales_order_order_n_1515f9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_status'], name='sales_order_deliver_2a662b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='sales_order_payment_ca014c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='sales_order_order_d_0a2432_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client'], name='sales_order_client__0a2b7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salescontractproduct',
            unique_together={('contract', 'product')},
        ),
        migrations.AddIndex(
            model_name='salesmovement',
            index=models.Index(fields=['estokada_processed'], name='sales_sales_estokad_f4609e_idx'),
        ),
    ]
