# Generated by Django 5.1.7 on 2025-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastruction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giving',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='giving',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Комментарий'),
        ),
    ]
