# Generated by Django 5.1.7 on 2025-04-16 15:35

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('infrastruction', '0002_remove_giving_employee_id_giving_comment'),
    ]

    operations = [
        # Fix the problematic operations from the previous migration
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='projectitem',
            options={'ordering': ['project', 'name'], 'verbose_name': 'Элемент проекта', 'verbose_name_plural': 'Элементы проекта'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['product__name'], 'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
        # Create ReceivingItem model first
        migrations.CreateModel(
            name='ReceivingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('unit_price', models.FloatField(verbose_name='Цена за единицу')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastruction.product', verbose_name='Продукт')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='infrastruction.receiving', verbose_name='Поступление')),
            ],
            options={
                'verbose_name': 'Элемент поступления',
                'verbose_name_plural': 'Элементы поступления',
                'ordering': ['id'],
            },
        ),
        # Now modify the receiving model
        migrations.AddField(
            model_name='receiving',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.RemoveField(
            model_name='receiving',
            name='product',
        ),
        migrations.RemoveField(
            model_name='receiving',
            name='quantity',
        ),
        # Fix other field changes
        migrations.AlterField(
            model_name='canteenexpense',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='canteenexpense',
            name='unit_price',
            field=models.FloatField(verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='giving',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='project_items/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='unit_price',
            field=models.FloatField(verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
    ]
