# Generated by Django 5.1.7 on 2025-04-16 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastruction', '0004_auto_20250416_2035'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('date_used', models.DateField(default=django.utils.timezone.now, verbose_name='Дата использования')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastruction.product', verbose_name='Продукт')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_products', to='infrastruction.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Использованный продукт',
                'verbose_name_plural': 'Использованные продукты',
                'ordering': ['-date_used', 'project'],
            },
        ),
    ]
