# Generated by Django 5.1.7 on 2025-05-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastruction', '0007_orderproduct_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'шт.'), ('kg', 'кг'), ('l', 'литр'), ('m', 'метр')], default='pcs', max_length=5, verbose_name='Единица измерения'),
        ),
    ]
