# Generated by Django 5.1.7 on 2025-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastruction', '0008_orderitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='receiving_photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'шт.'), ('kg', 'кг'), ('l', 'литр'), ('m', 'метр')], default='pcs', max_length=5, verbose_name='Единица измерения'),
        ),
    ]
