# Generated by Django 5.1.7 on 2025-03-25 07:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Klient nomi')),
            ],
        ),
        migrations.CreateModel(
            name='LocalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Klient nomi')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klientlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya')),
                ('volume', models.FloatField(default=0, verbose_name='Hajmi (l)')),
                ('weight', models.FloatField(default=0, verbose_name="Og'irligi (kg)")),
                ('density', models.FloatField(default=0, verbose_name='Zichlik (kg/l)')),
                ('specific_weight', models.FloatField(default=0, verbose_name="Udel Og'irligi")),
                ('price_usd', models.FloatField(blank=True, default=0, null=True, verbose_name='Narx (USD)')),
                ('price_sum', models.FloatField(blank=True, default=0, null=True, verbose_name="Narx (so'm)")),
                ('in_qty', models.FloatField(default=0, verbose_name='Umumiy kirim (qty)')),
                ('min_stock', models.FloatField(default=0, verbose_name='Minimum ruxsat etilgan qoldiq')),
                ('out_qty', models.FloatField(default=0, verbose_name='Umumiy chiqim (qty)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('zone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zona')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Wagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wagon_number', models.CharField(max_length=20, unique=True, verbose_name='Vagon raqami')),
                ('net_weight', models.FloatField(default=0, verbose_name="Netto og'irligi")),
                ('meter_weight', models.FloatField(default=0, verbose_name="Meter og'irligi")),
                ('capacity', models.FloatField(default=0, verbose_name="Sig'im (tonna)")),
                ('volume', models.FloatField(default=0, verbose_name='Hajmi (L)')),
                ('price_sum', models.FloatField(default=0, verbose_name="Umumiy summa (so'm)")),
                ('condition', models.CharField(default='Yaxshi', max_length=50, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Вагон',
                'verbose_name_plural': 'Вагонлар',
                'ordering': ['wagon_number'],
            },
        ),
        migrations.CreateModel(
            name='WagonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vagon turi')),
                ('meter_shtok_map', models.JSONField(blank=True, help_text="Masalan: {'1.0': 1000, '1.2':1200}, meter → litr", null=True)),
            ],
            options={
                'verbose_name': 'Vagon turi',
                'verbose_name_plural': 'Vagon turlari',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ombor nomi')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzil')),
                ('zone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zona')),
                ('location_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Location Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='Qoldiq (qty)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Partiya raqami')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='Ishlab chiqarilgan sana')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati')),
                ('in_qty', models.FloatField(default=0, verbose_name='Kirim (qty)')),
                ('out_qty', models.FloatField(default=0, verbose_name='Chiqim (qty)')),
                ('quantity', models.FloatField(default=0, verbose_name='Joriy qoldiq (qty)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партиялар',
                'unique_together': {('product', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rezervuar nomi')),
                ('capacity', models.FloatField(default=0, verbose_name="Sig'im (L yoki tonna)")),
                ('in_qty', models.FloatField(default=0, verbose_name='Kirim (qty)')),
                ('out_qty', models.FloatField(default=0, verbose_name='Chiqim (qty)')),
                ('quantity', models.FloatField(default=0, verbose_name='Joriy qoldiq (qty)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Saqlanayotgan mahsulot')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hujjat raqami')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('movement_type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], max_length=3, verbose_name='Harakat turi')),
                ('quantity', models.FloatField(default=0, verbose_name='Fakt tonna (qty)')),
                ('temperature', models.FloatField(blank=True, default=0, null=True, verbose_name='Temperatura')),
                ('density', models.FloatField(blank=True, default=0, null=True, verbose_name='Zichlik')),
                ('liter', models.FloatField(blank=True, default=0, null=True, verbose_name='Litr')),
                ('specific_weight', models.FloatField(blank=True, default=0, null=True, verbose_name="Udel og'irlik")),
                ('price_sum', models.FloatField(default=0, verbose_name="Narx (so'm)")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('doc_ton', models.FloatField(default=0, verbose_name="Hujjat bo'yicha ton")),
                ('difference_ton', models.FloatField(default=0, editable=False, verbose_name='Farq (ton)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.batch', verbose_name='Partiya')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.client', verbose_name='Klient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Mahsulot')),
                ('reservoir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.reservoir', verbose_name='Rezervuar')),
                ('wagon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.wagon', verbose_name='Vagon')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'Движение',
                'verbose_name_plural': 'Движения',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReservoirMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('movement_type', models.CharField(choices=[('in', "Kirim (to'ldirish)"), ('out', "Chiqim (bo'shatish)")], max_length=3, verbose_name='Harakat turi')),
                ('quantity', models.FloatField(verbose_name='Miqdor (qty)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Mahsulot')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.reservoir', verbose_name='Rezervuar')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='Qisman miqdor (litr yoki kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.movement', verbose_name='Harakat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Mahsulot')),
                ('reservoir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.reservoir', verbose_name='Rezervuar')),
                ('wagon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.wagon', verbose_name='Vagon')),
            ],
        ),
        migrations.CreateModel(
            name='LocalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('density', models.FloatField(default=0, verbose_name='Zichlik (Удел)')),
                ('temperature', models.FloatField(default=0, verbose_name='Temperatura (C)')),
                ('liter', models.FloatField(default=0, verbose_name='Litr')),
                ('mass', models.FloatField(default=0, verbose_name='Massa (kg)')),
                ('specific_weight', models.FloatField(blank=True, default=0, null=True, verbose_name="Udel og'irlik")),
                ('doc_ton', models.FloatField(default=0, verbose_name="Hujjat bo'yicha ton")),
                ('quantity', models.FloatField(default=0, verbose_name='Fakt tonna (qty)')),
                ('difference_ton', models.FloatField(default=0, editable=False, verbose_name='Farq (ton)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.localclient', verbose_name='Klient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Mahsulot')),
                ('wagon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.wagon', verbose_name='Vagon')),
            ],
            options={
                'verbose_name': 'Mahalliy Harakat',
                'verbose_name_plural': 'Mahalliy Harakatlar',
            },
        ),
        migrations.AddField(
            model_name='wagon',
            name='wagon_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.wagontype', verbose_name='Vagon tipi'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Ombor'),
        ),
    ]
