# Generated by Django 5.1.7 on 2025-03-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_localmovement_reservoir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localmovement',
            name='mass',
        ),
        migrations.AddField(
            model_name='localmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], default='in', max_length=3, verbose_name='Harakat turi'),
        ),
        migrations.AlterField(
            model_name='localmovement',
            name='density',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Zichlik'),
        ),
        migrations.AlterField(
            model_name='localmovement',
            name='liter',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Litr'),
        ),
        migrations.AlterField(
            model_name='localmovement',
            name='reservoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.reservoir', verbose_name='Rezervuar'),
        ),
        migrations.AlterField(
            model_name='localmovement',
            name='temperature',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Temperatura (C)'),
        ),
    ]
