# Generated by Django 5.1.7 on 2025-03-28 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse', verbose_name='Ombor'),
        ),
    ]
