# Generated by Django 5.1.7 on 2025-03-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_transport_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservoir',
            options={'verbose_name': 'Rezervuar', 'verbose_name_plural': 'Rezervuarlar'},
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='in_qty',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='out_qty',
        ),
        migrations.RemoveField(
            model_name='reservoir',
            name='quantity',
        ),
        migrations.AddField(
            model_name='reservoir',
            name='current_volume',
            field=models.FloatField(default=0, verbose_name='Joriy hajm'),
        ),
        migrations.AddField(
            model_name='reservoir',
            name='meter_shtok_map',
            field=models.JSONField(blank=True, default=dict, verbose_name="Kalibrovka ma'lumotlari"),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='capacity',
            field=models.FloatField(verbose_name="Sig'im (tonna)"),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product', verbose_name='Mahsulot'),
        ),
    ]
