# Generated by Django 5.1.7 on 2025-03-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_reservoir_options_remove_reservoir_in_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='doc_ton',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Документированный тоннаж'),
        ),
    ]
