# Generated by Django 5.1.7 on 2025-03-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_movement_doc_ton'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservoir',
            name='current_quantity',
            field=models.FloatField(default=0, verbose_name='Joriy miqdor (qty)'),
        ),
        migrations.AddField(
            model_name='wagon',
            name='current_quantity',
            field=models.FloatField(default=0, verbose_name='Joriy miqdor (qty)'),
        ),
    ]
