# Generated by Django 5.1.7 on 2025-04-10 08:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_reservoir_current_quantity_wagon_current_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='difference_ton',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='doc_ton',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='reservoir',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='wagon',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='movement',
            name='client_type',
            field=models.CharField(blank=True, choices=[('local', 'Локальный'), ('international', 'Международный')], max_length=15, null=True, verbose_name='Тип клиента'),
        ),
        migrations.AddField(
            model_name='movement',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_movements', to=settings.AUTH_USER_MODEL, verbose_name='Подтверждено пользователем'),
        ),
        migrations.AddField(
            model_name='movement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AddField(
            model_name='movement',
            name='difference',
            field=models.FloatField(default=0, editable=False, verbose_name='Разница'),
        ),
        migrations.AddField(
            model_name='movement',
            name='expected_quantity',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ожидаемое количество (по документам)'),
        ),
        migrations.AddField(
            model_name='movement',
            name='price_usd',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена (USD)'),
        ),
        migrations.AddField(
            model_name='movement',
            name='production_loss',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Потери при производстве'),
        ),
        migrations.AddField(
            model_name='movement',
            name='production_loss_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина потерь'),
        ),
        migrations.AddField(
            model_name='movement',
            name='source_reservoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_movements', to='warehouse.reservoir', verbose_name='Исходный резервуар'),
        ),
        migrations.AddField(
            model_name='movement',
            name='source_wagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_movements', to='warehouse.wagon', verbose_name='Исходный вагон'),
        ),
        migrations.AddField(
            model_name='movement',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_movements', to='warehouse.warehouse', verbose_name='Исходный склад'),
        ),
        migrations.AddField(
            model_name='movement',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('confirmed', 'Подтвержден'), ('processed', 'Обработан'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='created', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='movement',
            name='target_reservoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_movements', to='warehouse.reservoir', verbose_name='Целевой резервуар'),
        ),
        migrations.AddField(
            model_name='movement',
            name='target_wagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_movements', to='warehouse.wagon', verbose_name='Целевой вагон'),
        ),
        migrations.AddField(
            model_name='movement',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_movements', to='warehouse.warehouse', verbose_name='Целевой склад'),
        ),
        migrations.AddField(
            model_name='movement',
            name='transport_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер транспортного средства'),
        ),
        migrations.AddField(
            model_name='movement',
            name='transport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='transport_photos/', verbose_name='Фото транспорта'),
        ),
        migrations.AddField(
            model_name='movement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.batch', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='density',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Плотность'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='liter',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Объем (литры)'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Приёмка'), ('out', 'Продажа'), ('production', 'Производство'), ('transfer', 'Перемещение')], max_length=10, verbose_name='Тип движения'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='price_sum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена (сум)'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Фактическое количество (тонн)'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='specific_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Удельный вес'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='temperature',
            field=models.FloatField(blank=True, default=20, null=True, verbose_name='Температура'),
        ),
    ]
