# Generated by Django 5.1.7 on 2025-04-10 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_analyticsreport_productionsource_analyticsdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='planned', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_audits', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMinLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Минимальный остаток')),
                ('optimal_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Оптимальный остаток')),
                ('max_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Максимальный остаток')),
                ('alert_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('alert_threshold', models.IntegerField(default=10, verbose_name='Порог уведомления (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='min_level', to='warehouse.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Минимальный уровень продукта',
                'verbose_name_plural': 'Минимальные уровни продуктов',
            },
        ),
        migrations.CreateModel(
            name='PurchasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('plan_date', models.DateField(verbose_name='Дата плана')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'План закупок',
                'verbose_name_plural': 'Планы закупок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('expected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Учетное количество')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Фактическое количество')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.inventoryaudit', verbose_name='Инвентаризация')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция инвентаризации',
                'verbose_name_plural': 'Позиции инвентаризации',
                'unique_together': {('audit', 'product', 'location')},
            },
        ),
        migrations.CreateModel(
            name='PurchasePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Количество')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='Автоматически сформирован')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.purchaseplan', verbose_name='План закупок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция плана закупок',
                'verbose_name_plural': 'Позиции плана закупок',
                'ordering': ['priority'],
                'unique_together': {('plan', 'product')},
            },
        ),
        migrations.CreateModel(
            name='StockForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('forecasted_quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Прогнозируемое количество')),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Уровень уверенности (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='warehouse.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Прогноз запасов',
                'verbose_name_plural': 'Прогнозы запасов',
                'ordering': ['date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
