# Generated by Django 5.1.7 on 2025-04-10 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_inventoryaudit_productminlevel_purchaseplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('website', models.URLField(blank=True, verbose_name='Вебсайт')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_point', models.DecimalField(decimal_places=2, help_text='Количество, при котором нужно делать заказ', max_digits=10, verbose_name='Точка заказа')),
                ('safety_stock', models.DecimalField(decimal_places=2, help_text='Минимальный запас для непредвиденных ситуаций', max_digits=10, verbose_name='Страховой запас')),
                ('order_quantity', models.DecimalField(decimal_places=2, help_text='Рекомендуемое количество для заказа', max_digits=10, verbose_name='Количество заказа')),
                ('lead_time_demand', models.DecimalField(decimal_places=2, help_text='Среднее потребление за время ожидания поставки', max_digits=10, verbose_name='Потребление за время поставки')),
                ('auto_order', models.BooleanField(default=False, help_text='Формировать заказ автоматически при достижении точки заказа', verbose_name='Автоматический заказ')),
                ('last_calculation', models.DateTimeField(blank=True, null=True, verbose_name='Последний расчет')),
                ('notify_emails', models.TextField(blank=True, help_text='Перечислите email через запятую', verbose_name='Email для уведомлений')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_point', to='warehouse.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Точка заказа',
                'verbose_name_plural': 'Точки заказа',
            },
        ),
        migrations.CreateModel(
            name='PurchaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Необходимое количество')),
                ('recommended_order_date', models.DateField(verbose_name='Рекомендуемая дата заказа')),
                ('expected_delivery_date', models.DateField(verbose_name='Ожидаемая дата поставки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('acknowledged', 'Принято к сведению'), ('ordered', 'Заказано'), ('canceled', 'Отменено')], default='pending', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('notified_users', models.ManyToManyField(blank=True, related_name='purchase_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Уведомленные пользователи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_notifications', to='warehouse.product', verbose_name='Продукт')),
                ('recommended_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_recommendations', to='warehouse.supplier', verbose_name='Рекомендуемый поставщик')),
            ],
            options={
                'verbose_name': 'Уведомление о закупке',
                'verbose_name_plural': 'Уведомления о закупках',
                'ordering': ['recommended_order_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена закупки')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='Предпочтительный поставщик')),
                ('min_order_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальное количество заказа')),
                ('lead_time', models.IntegerField(blank=True, null=True, verbose_name='Срок поставки (дни)')),
                ('last_order_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего заказа')),
                ('last_price_update', models.DateField(blank=True, null=True, verbose_name='Дата последнего обновления цены')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='warehouse.product', verbose_name='Продукт')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='warehouse.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик продукта',
                'verbose_name_plural': 'Поставщики продуктов',
                'unique_together': {('product', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='SupplierRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], verbose_name='Оценка')),
                ('category', models.CharField(choices=[('quality', 'Качество продукции'), ('delivery', 'Своевременность поставки'), ('price', 'Цена'), ('communication', 'Коммуникация'), ('overall', 'Общая оценка')], max_length=100, verbose_name='Категория оценки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Кто оценил')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='warehouse.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Оценка поставщика',
                'verbose_name_plural': 'Оценки поставщиков',
                'unique_together': {('supplier', 'category', 'created_by', 'created_at')},
            },
        ),
    ]
