# Generated by Django 5.1.7 on 2025-04-11 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_supplier_orderpoint_purchasenotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='local_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.localclient', verbose_name='Локальный клиент'),
        ),
    ]
