# Generated by Django 5.1.7 on 2025-05-05 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstokadaMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_weight', models.FloatField(verbose_name='Фактический вес')),
                ('document_weight', models.FloatField(verbose_name='Документальный вес')),
                ('weight_difference', models.FloatField(editable=False, verbose_name='Разница (авторасчет)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Температура')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='Удельный вес')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='estokada_photos/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesmovement', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Движение через эстокаду',
                'verbose_name_plural': 'Движения через эстокаду',
                'ordering': ['-created_at'],
            },
        ),
    ]
